import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

// Components 
import NavBar from "./components/Navbar"

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
